"""Failure gallery (A-3): the worst N cases, with the explanation shown and
a templated one-line note each. Cheap, and the spec calls it out as the
section examiners read most carefully.
"""
from __future__ import annotations

import os
import numpy as np
from PIL import Image

from ..config import DataConfig, DOCS_DIR
from ..data import read_manifest, load_image
from ..models.baseline import XAIModel
from ..explain.registry import explain as registry_explain
from ..explain._common import overlay

GALLERY_IMAGE_DIR = os.path.join(os.path.dirname(DOCS_DIR), 'app', 'static', 'audit')


def _note(true_label: str, pred_label: str, proba: float) -> str:
    kind = 'false positive' if (true_label == 'NORMAL' and pred_label == 'PNEUMONIA') else 'false negative'
    return (f'{kind.capitalize()}: true label {true_label}, predicted {pred_label} '
            f'at {proba:.1%} confidence in the predicted class.')


def build_failure_gallery(xai_model: XAIModel, cfg: DataConfig | None = None, split: str = 'test',
                           method: str = 'gradcam', n: int = 10, threshold: float = 0.5,
                           out_dir: str = GALLERY_IMAGE_DIR, docs_path: str | None = None) -> str:
    cfg = cfg or DataConfig.load()
    os.makedirs(out_dir, exist_ok=True)
    rows = read_manifest(split)

    scored = []
    for relpath, label in rows:
        path = os.path.join(cfg.dataset_dir, relpath)
        img = load_image(path, cfg.img_size)
        proba = float(xai_model.proba(img[np.newaxis])[0])
        pred_label = 'PNEUMONIA' if proba > threshold else 'NORMAL'
        is_error = pred_label != label
        confidence_in_pred = proba if pred_label == 'PNEUMONIA' else 1 - proba
        scored.append((relpath, label, pred_label, proba, confidence_in_pred, is_error))

    errors = sorted((r for r in scored if r[5]), key=lambda r: -r[4])[:n]

    lines = [
        '# Failure gallery (A-3)',
        '',
        f'The {len(errors)} worst-confidence errors on the `{split}` split, method: `{method}`.',
        'Generated by `xai_cxr.audits.failure_gallery.build_failure_gallery` — regenerate after any '
        'retrain rather than editing by hand.',
        '',
    ]
    for i, (relpath, label, pred_label, proba, conf, _) in enumerate(errors):
        path = os.path.join(cfg.dataset_dir, relpath)
        img = load_image(path, cfg.img_size)
        heatmap = registry_explain(method, xai_model, img, img_size=cfg.img_size)
        blended = overlay(img, heatmap)
        img_name = f'failure_{i:02d}.png'
        Image.fromarray(blended).save(os.path.join(out_dir, img_name))

        lines.append(f'## Case {i + 1}: `{relpath}`')
        lines.append('')
        lines.append(f'![{img_name}](../app/static/audit/{img_name})')
        lines.append('')
        lines.append(_note(label, pred_label, conf))
        lines.append('')

    docs_path = docs_path or os.path.join(DOCS_DIR, 'failure_gallery.md')
    os.makedirs(os.path.dirname(docs_path), exist_ok=True)
    with open(docs_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return docs_path
